spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
       # enable_lazy_load_no_trans: true
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/appoint
    username: postgres
    password: postgres
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

server:
  port: 8081